export {
  ADMIN_SCOPE,
  READ_SCOPE,
  WRITE_SCOPE,
  SESSION_READ_SCOPE,
  SESSION_WRITE_SCOPE,
  APPROVALS_SCOPE,
  QUESTIONS_SCOPE,
  PAIRING_SCOPE,
  TALK_SCOPE,
  TALK_SECRETS_SCOPE,
  hasGatewayAdminScope,
  isOperatorScope,
  normalizeOperatorScopeList,
  type OperatorScope,
} from "../../packages/gateway-protocol/src/operator-scopes.js";
